#!/usr/bin/env sh

. ./lib/mgmt.sh

print_error() {
	printf 'ERROR: %s requires a project name.\n' "$1" >&2
}

show_help() {
	printf 'Help has arrived!\n'
}

while :; do
	case $1 in
	-h | -\? | --help | help)
		show_help
		exit
		;;
	check | check_for_project)
		if [ -n "$2" ]; then
			shift
			check_for_project "$@"
		else
			print_error "$1"
			exit 1
		fi
		;;
	new | new_project)
		if [ -n "$2" ]; then
			shift
			new_project "$@"
		else
			print_error "$1"
			exit 1
		fi
		;;
	load | load_project)
		if [ -n "$2" ]; then
			shift
			load_project "$@"
		else
			print_error "$1"
			exit 1
		fi
		;;
	edit | edit_project)
		if [ -n "$2" ]; then
			shift
			edit_project "$@"
		else
			print_error "$1"
			exit 1
		fi
		;;
	--) # End of all options. Passthru additional options to tmux?
		shift
		break
		;;
	-?*)
		printf 'ERROR: Unknown option: %s\n' "$1" >&2
		exit 1
		;;
	*) # Default case: If no more options then break out of the loop.
		break ;;
	esac

	shift
done
